/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminTaxRouteImport } from './routes/_authenticated/admin.tax'
import { Route as AuthenticatedAdminSubscriptionRouteImport } from './routes/_authenticated/admin.subscription'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin.maintenance'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminEquipmentRouteImport } from './routes/_authenticated/admin.equipment'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCollectEquipmentRouteImport } from './routes/_authenticated/admin.collect-equipment'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminBookNowRouteImport } from './routes/_authenticated/admin.book-now'
import { Route as AuthenticatedAdminReportsIndexRouteImport } from './routes/_authenticated/admin.reports.index'
import { Route as AuthenticatedAdminReportsRevenueRouteImport } from './routes/_authenticated/admin.reports.revenue'
import { Route as AuthenticatedAdminReportsPaymentsRouteImport } from './routes/_authenticated/admin.reports.payments'
import { Route as AuthenticatedAdminReportsMaintenanceRouteImport } from './routes/_authenticated/admin.reports.maintenance'
import { Route as AuthenticatedAdminReportsInvoicesRouteImport } from './routes/_authenticated/admin.reports.invoices'
import { Route as AuthenticatedAdminReportsEquipmentRouteImport } from './routes/_authenticated/admin.reports.equipment'
import { Route as AuthenticatedAdminReportsCustomersRouteImport } from './routes/_authenticated/admin.reports.customers'
import { Route as AuthenticatedAdminReportsBookingsRouteImport } from './routes/_authenticated/admin.reports.bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTaxRoute = AuthenticatedAdminTaxRouteImport.update({
  id: '/admin/tax',
  path: '/admin/tax',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSubscriptionRoute =
  AuthenticatedAdminSubscriptionRouteImport.update({
    id: '/admin/subscription',
    path: '/admin/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/admin/maintenance',
    path: '/admin/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/admin/invoices',
    path: '/admin/invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEquipmentRoute =
  AuthenticatedAdminEquipmentRouteImport.update({
    id: '/admin/equipment',
    path: '/admin/equipment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCollectEquipmentRoute =
  AuthenticatedAdminCollectEquipmentRouteImport.update({
    id: '/admin/collect-equipment',
    path: '/admin/collect-equipment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/admin/branches',
    path: '/admin/branches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/admin/bookings',
    path: '/admin/bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBookNowRoute =
  AuthenticatedAdminBookNowRouteImport.update({
    id: '/admin/book-now',
    path: '/admin/book-now',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsIndexRoute =
  AuthenticatedAdminReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsRevenueRoute =
  AuthenticatedAdminReportsRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsPaymentsRoute =
  AuthenticatedAdminReportsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsMaintenanceRoute =
  AuthenticatedAdminReportsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsInvoicesRoute =
  AuthenticatedAdminReportsInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsEquipmentRoute =
  AuthenticatedAdminReportsEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsCustomersRoute =
  AuthenticatedAdminReportsCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)
const AuthenticatedAdminReportsBookingsRoute =
  AuthenticatedAdminReportsBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AuthenticatedAboutRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/book-now': typeof AuthenticatedAdminBookNowRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/collect-equipment': typeof AuthenticatedAdminCollectEquipmentRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRouteWithChildren
  '/admin/subscription': typeof AuthenticatedAdminSubscriptionRoute
  '/admin/tax': typeof AuthenticatedAdminTaxRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/reports/bookings': typeof AuthenticatedAdminReportsBookingsRoute
  '/admin/reports/customers': typeof AuthenticatedAdminReportsCustomersRoute
  '/admin/reports/equipment': typeof AuthenticatedAdminReportsEquipmentRoute
  '/admin/reports/invoices': typeof AuthenticatedAdminReportsInvoicesRoute
  '/admin/reports/maintenance': typeof AuthenticatedAdminReportsMaintenanceRoute
  '/admin/reports/payments': typeof AuthenticatedAdminReportsPaymentsRoute
  '/admin/reports/revenue': typeof AuthenticatedAdminReportsRevenueRoute
  '/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AuthenticatedAboutRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/admin/book-now': typeof AuthenticatedAdminBookNowRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/collect-equipment': typeof AuthenticatedAdminCollectEquipmentRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/subscription': typeof AuthenticatedAdminSubscriptionRoute
  '/admin/tax': typeof AuthenticatedAdminTaxRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/reports/bookings': typeof AuthenticatedAdminReportsBookingsRoute
  '/admin/reports/customers': typeof AuthenticatedAdminReportsCustomersRoute
  '/admin/reports/equipment': typeof AuthenticatedAdminReportsEquipmentRoute
  '/admin/reports/invoices': typeof AuthenticatedAdminReportsInvoicesRoute
  '/admin/reports/maintenance': typeof AuthenticatedAdminReportsMaintenanceRoute
  '/admin/reports/payments': typeof AuthenticatedAdminReportsPaymentsRoute
  '/admin/reports/revenue': typeof AuthenticatedAdminReportsRevenueRoute
  '/admin/reports': typeof AuthenticatedAdminReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/book-now': typeof AuthenticatedAdminBookNowRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/collect-equipment': typeof AuthenticatedAdminCollectEquipmentRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRouteWithChildren
  '/_authenticated/admin/subscription': typeof AuthenticatedAdminSubscriptionRoute
  '/_authenticated/admin/tax': typeof AuthenticatedAdminTaxRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/reports/bookings': typeof AuthenticatedAdminReportsBookingsRoute
  '/_authenticated/admin/reports/customers': typeof AuthenticatedAdminReportsCustomersRoute
  '/_authenticated/admin/reports/equipment': typeof AuthenticatedAdminReportsEquipmentRoute
  '/_authenticated/admin/reports/invoices': typeof AuthenticatedAdminReportsInvoicesRoute
  '/_authenticated/admin/reports/maintenance': typeof AuthenticatedAdminReportsMaintenanceRoute
  '/_authenticated/admin/reports/payments': typeof AuthenticatedAdminReportsPaymentsRoute
  '/_authenticated/admin/reports/revenue': typeof AuthenticatedAdminReportsRevenueRoute
  '/_authenticated/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/profile'
    | '/auth/callback'
    | '/auth/'
    | '/admin/book-now'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/collect-equipment'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/subscription'
    | '/admin/tax'
    | '/admin/team'
    | '/admin/reports/bookings'
    | '/admin/reports/customers'
    | '/admin/reports/equipment'
    | '/admin/reports/invoices'
    | '/admin/reports/maintenance'
    | '/admin/reports/payments'
    | '/admin/reports/revenue'
    | '/admin/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/profile'
    | '/auth/callback'
    | '/auth'
    | '/admin/book-now'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/collect-equipment'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/subscription'
    | '/admin/tax'
    | '/admin/team'
    | '/admin/reports/bookings'
    | '/admin/reports/customers'
    | '/admin/reports/equipment'
    | '/admin/reports/invoices'
    | '/admin/reports/maintenance'
    | '/admin/reports/payments'
    | '/admin/reports/revenue'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/about'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/auth/'
    | '/_authenticated/admin/book-now'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/collect-equipment'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/equipment'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/subscription'
    | '/_authenticated/admin/tax'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/reports/bookings'
    | '/_authenticated/admin/reports/customers'
    | '/_authenticated/admin/reports/equipment'
    | '/_authenticated/admin/reports/invoices'
    | '/_authenticated/admin/reports/maintenance'
    | '/_authenticated/admin/reports/payments'
    | '/_authenticated/admin/reports/revenue'
    | '/_authenticated/admin/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tax': {
      id: '/_authenticated/admin/tax'
      path: '/admin/tax'
      fullPath: '/admin/tax'
      preLoaderRoute: typeof AuthenticatedAdminTaxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subscription': {
      id: '/_authenticated/admin/subscription'
      path: '/admin/subscription'
      fullPath: '/admin/subscription'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/equipment': {
      id: '/_authenticated/admin/equipment'
      path: '/admin/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/collect-equipment': {
      id: '/_authenticated/admin/collect-equipment'
      path: '/admin/collect-equipment'
      fullPath: '/admin/collect-equipment'
      preLoaderRoute: typeof AuthenticatedAdminCollectEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/book-now': {
      id: '/_authenticated/admin/book-now'
      path: '/admin/book-now'
      fullPath: '/admin/book-now'
      preLoaderRoute: typeof AuthenticatedAdminBookNowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports/': {
      id: '/_authenticated/admin/reports/'
      path: '/'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AuthenticatedAdminReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/revenue': {
      id: '/_authenticated/admin/reports/revenue'
      path: '/revenue'
      fullPath: '/admin/reports/revenue'
      preLoaderRoute: typeof AuthenticatedAdminReportsRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/payments': {
      id: '/_authenticated/admin/reports/payments'
      path: '/payments'
      fullPath: '/admin/reports/payments'
      preLoaderRoute: typeof AuthenticatedAdminReportsPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/maintenance': {
      id: '/_authenticated/admin/reports/maintenance'
      path: '/maintenance'
      fullPath: '/admin/reports/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminReportsMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/invoices': {
      id: '/_authenticated/admin/reports/invoices'
      path: '/invoices'
      fullPath: '/admin/reports/invoices'
      preLoaderRoute: typeof AuthenticatedAdminReportsInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/equipment': {
      id: '/_authenticated/admin/reports/equipment'
      path: '/equipment'
      fullPath: '/admin/reports/equipment'
      preLoaderRoute: typeof AuthenticatedAdminReportsEquipmentRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/customers': {
      id: '/_authenticated/admin/reports/customers'
      path: '/customers'
      fullPath: '/admin/reports/customers'
      preLoaderRoute: typeof AuthenticatedAdminReportsCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
    '/_authenticated/admin/reports/bookings': {
      id: '/_authenticated/admin/reports/bookings'
      path: '/bookings'
      fullPath: '/admin/reports/bookings'
      preLoaderRoute: typeof AuthenticatedAdminReportsBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
  }
}

interface AuthenticatedAdminReportsRouteChildren {
  AuthenticatedAdminReportsBookingsRoute: typeof AuthenticatedAdminReportsBookingsRoute
  AuthenticatedAdminReportsCustomersRoute: typeof AuthenticatedAdminReportsCustomersRoute
  AuthenticatedAdminReportsEquipmentRoute: typeof AuthenticatedAdminReportsEquipmentRoute
  AuthenticatedAdminReportsInvoicesRoute: typeof AuthenticatedAdminReportsInvoicesRoute
  AuthenticatedAdminReportsMaintenanceRoute: typeof AuthenticatedAdminReportsMaintenanceRoute
  AuthenticatedAdminReportsPaymentsRoute: typeof AuthenticatedAdminReportsPaymentsRoute
  AuthenticatedAdminReportsRevenueRoute: typeof AuthenticatedAdminReportsRevenueRoute
  AuthenticatedAdminReportsIndexRoute: typeof AuthenticatedAdminReportsIndexRoute
}

const AuthenticatedAdminReportsRouteChildren: AuthenticatedAdminReportsRouteChildren =
  {
    AuthenticatedAdminReportsBookingsRoute:
      AuthenticatedAdminReportsBookingsRoute,
    AuthenticatedAdminReportsCustomersRoute:
      AuthenticatedAdminReportsCustomersRoute,
    AuthenticatedAdminReportsEquipmentRoute:
      AuthenticatedAdminReportsEquipmentRoute,
    AuthenticatedAdminReportsInvoicesRoute:
      AuthenticatedAdminReportsInvoicesRoute,
    AuthenticatedAdminReportsMaintenanceRoute:
      AuthenticatedAdminReportsMaintenanceRoute,
    AuthenticatedAdminReportsPaymentsRoute:
      AuthenticatedAdminReportsPaymentsRoute,
    AuthenticatedAdminReportsRevenueRoute:
      AuthenticatedAdminReportsRevenueRoute,
    AuthenticatedAdminReportsIndexRoute: AuthenticatedAdminReportsIndexRoute,
  }

const AuthenticatedAdminReportsRouteWithChildren =
  AuthenticatedAdminReportsRoute._addFileChildren(
    AuthenticatedAdminReportsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminBookNowRoute: typeof AuthenticatedAdminBookNowRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCollectEquipmentRoute: typeof AuthenticatedAdminCollectEquipmentRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEquipmentRoute: typeof AuthenticatedAdminEquipmentRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRouteWithChildren
  AuthenticatedAdminSubscriptionRoute: typeof AuthenticatedAdminSubscriptionRoute
  AuthenticatedAdminTaxRoute: typeof AuthenticatedAdminTaxRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminBookNowRoute: AuthenticatedAdminBookNowRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCollectEquipmentRoute:
    AuthenticatedAdminCollectEquipmentRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEquipmentRoute: AuthenticatedAdminEquipmentRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRouteWithChildren,
  AuthenticatedAdminSubscriptionRoute: AuthenticatedAdminSubscriptionRoute,
  AuthenticatedAdminTaxRoute: AuthenticatedAdminTaxRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
